spring:
  application:
    name: findex

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.rfxmuflolfcoedwishiu
    password: findexadmin1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50            # 한 번에 묶을 크기
          order_inserts: true          # insert 문 정렬 (배치 필수)
          order_updates: true
    open-in-view: false
openapi:
  base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
  service-key: a9ed745a7406899751cf4c7c8c957700ecceb8fb669eee383a358336e12157bf
findex:
  batch:
    cron: "* * 0 * * *" #
#외부 프록시 넘겨주는 설정 추가
server:
  forward-headers-strategy: native
