spring:
  application:
    name: findex

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.rfxmuflolfcoedwishiu
    password: findexadmin1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

findex:
  batch:
    cron: "5 * * * * *" #
